### ISSUE TITLE
This programm didnt support c well

### ISSUE THREAD

**Issue by e361** [m3gofriends/Python3-PlainTextBeautify#3]
look at the picture, many operator give in wrong positon and precedence.
![Screenshot from 2020-11-02 14-07-23](https://user-images.githubusercontent.com/9514508/97835268-bf3e1380-1d14-11eb-95b7-8b6c422fbeaa.png)

**Comment by e361** [comment]
**another problem!**
![Screenshot from 2020-11-02 15-19-03](https://user-images.githubusercontent.com/9514508/97840343-c79b4c00-1d1e-11eb-9b5f-d2ee26a5dd56.png)

**Comment by m3gofriends** [comment]
Version1.6 have fixed this problem.
Do you have any other questions?

**Comment by e361** [comment]
why all answer like the same??

**Comment by m3gofriends** [comment]
Because my English is sucks
