### ISSUE TITLE
Another Error!

### ISSUE THREAD

**Issue by e361** [m3gofriends/Python3-PlainTextBeautify#4]
while i typing "2" , the program seems no reponse!
And also, if i take input with some string, the program crashed, oops
![Screenshot from 2020-11-02 14-24-30](https://user-images.githubusercontent.com/9514508/97836368-2230aa00-1d17-11eb-93b9-063b80ac0990.png)

**Comment by m3gofriends** [comment]
Version 1.3 have fixed the input error!
Do you have any other questions?

**Comment by e361** [comment]
nah, thanks
